common/models/GalleryAlbum.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "gallery_albums".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $logo
 *
 * @property AlbumImage[] $albumImages
 */
class GalleryAlbum extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery_albums';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'logo'], 'required'],
            [['title', 'description', 'logo'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'logo' => 'Logo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlbumImages()
    {
        return $this->hasMany(AlbumImage::className(), ['album_id' => 'id']);
    }
}

backend/controllers/GalleryAlbumController.php
<?php

namespace backend\controllers;

use common\models\AlbumImage;
use Yii;
use common\models\GalleryAlbum;
use backend\models\GalleryAlbumSearch;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * GalleryAlbumController implements the CRUD actions for GalleryAlbum model.
 */
class GalleryAlbumController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all GalleryAlbum models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GalleryAlbumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new GalleryAlbum model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new GalleryAlbum();
        $albumImage = new AlbumImage();

        if ($_POST) {
            $model->title = $_POST['GalleryAlbum']['title'];
            $model->description = $_POST['GalleryAlbum']['description'];
            $model->logo = $_POST['GalleryAlbum']['logo'];
            if($model->validate()) {
                $model->save();
                if(!file_exists('gallery/' . $model->id)) {
                    mkdir('gallery/' . $model->id, 0777, true);
                }
                $imageInstances = UploadedFile::getInstancesByName('images');

                /** @var UploadedFile $imageInstance */
                foreach ($imageInstances as $imageInstance) {
//                    $this->createThumbImage($imageInstance);
                    $albumImage = new AlbumImage();
                    $albumImage->album_id = $model->id;
                    $albumImage->image = $imageInstance;
                    $albumImage->image
                        ->saveAs('gallery/' . $model->id . '/' . $imageInstance->getBaseName() . '.' . $imageInstance->getExtension());
                    $this->createThumbImage($imageInstance->name, $model->id);
                    $albumImage->save();
                }
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'albumImage' => $albumImage
            ]);
        }
    }

    /**
     * Updates an existing GalleryAlbum model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($_POST) {
            $model->title = $_POST['GalleryAlbum']['title'];
            $model->description = $_POST['GalleryAlbum']['description'];
            $model->logo = $_POST['GalleryAlbum']['logo'];
            if($model->validate()) {
                $model->save();
                if(!file_exists('gallery/' . $model->id)) {
                    mkdir('gallery/' . $model->id, 0777, true);
                }
                $imageInstances = UploadedFile::getInstancesByName('images');

                /** @var UploadedFile $imageInstance */
                foreach ($imageInstances as $imageInstance) {
                    $albumImage = new AlbumImage();
                    $albumImage->album_id = $model->id;
                    $albumImage->image = $imageInstance;
                    $albumImage->image
                        ->saveAs('gallery/' . $model->id . '/' . $imageInstance->getBaseName() . '.' . $imageInstance->getExtension());
                    $this->createThumbImage($imageInstance->name, $model->id);
                    $albumImage->save();
                }
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing GalleryAlbum model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        foreach($this->findModel($id)->albumImages as $image) {
            if($this->deleteDirectory('gallery/' . $id)) {
                $image->delete();
            }
        }
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionRemove() {
        if($id = $_POST['id']) {
            $album = AlbumImage::findOne($id);
            file_exists('gallery/' . $album->album_id . '/' . $album->image) ? unlink('gallery/' . $album->album_id .
                '/' . $album->image) : null;
            file_exists('gallery/' . $album->album_id . '/thumb/' . $album->image) ? unlink('gallery/' . $album->album_id .
                '/thumb/' . $album->image) : null;
            $album->delete();
            return true;
        }
        return false;
    }

    /**
     * Finds the GalleryAlbum model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GalleryAlbum the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = GalleryAlbum::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @param $fileName
     * @param $albumId
     */
    private function createThumbImage($fileName, $albumId) {
        $filePath = 'gallery/' . $albumId . '/' . $fileName;
        list($width, $height) = getimagesize('gallery/' . $albumId . '/' . $fileName);
        $newHeight = 150;
        $ratio = $newHeight / $height;
        $newWidth = $width * $ratio;
        $image_p = imagecreatetruecolor($newWidth, $newHeight);
        $image = imagecreatefromjpeg($filePath);
        imagecopyresampled($image_p, $image, 0, 0, 0, 0, $newWidth, $newHeight, $width, $height);
        if(!file_exists('gallery/' . $albumId . '/thumb/')) {
            mkdir('gallery/' . $albumId . '/thumb/', 0777, true);
        }
        imagejpeg($image_p, 'gallery/' . $albumId . '/thumb/' . $fileName, 100);
    }

    /**
     * @param $dir
     * @return bool
     */
    private function deleteDirectory($dir) {
        if (!file_exists($dir)) {
            return true;
        }

        if (!is_dir($dir)) {
            return unlink($dir);
        }

        foreach (scandir($dir) as $item) {
            if ($item == '.' || $item == '..') {
                continue;
            }

            if (!$this->deleteDirectory($dir . DIRECTORY_SEPARATOR . $item)) {
                return false;
            }

        }

        return rmdir($dir);
    }
}

backend/views/gallery-album/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use dosamigos\fileupload\FileUpload;
use dosamigos\fileupload\FileUploadUI;

/* @var $this yii\web\View */
/* @var $model common\models\GalleryAlbum */
/* @var $albumImage common\models\AlbumImage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-album-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'logo')->widget(InputFile::className(), [
        'controller' => 'elfinder-gallery',
        'filter' => 'image',
        'path' => $model->id ? $model->id : 'logos',
//        'path' => 'logos',
        'template' => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
        'options' => ['class' => 'form-control', 'readonly' => 'readonly'],
        'buttonOptions' => ['class' => 'btn btn-default'],
        'multiple' => false
    ]); ?>

    <div class="form-group field-galleryalbum-logo has-success">
        <label class="control-label" for="galleryalbum-logo">Images</label>

<?php
    $previewImages = [];
    /** @var \common\models\AlbumImage $image */
    foreach($model->albumImages as $image) {
        $previewImages[] = '<div><div onclick="removeImg('.$image->id.',$(this))" class="remove-button"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></div>' . Html::img(Yii::$app->params['backendUrl'] . '/gallery/' . $model->id . '/thumb/' . $image->image, ['class' => 'file-preview-image', 'alt' => '']) . '</div>';
    } ?>
    <?= \kartik\file\FileInput::widget([
        'name' => 'images[]',
        'options' => ['multiple' => true, 'accept' => 'image/*'],
        'pluginOptions' => [
            'previewFileType' => 'image',
            'showUpload' => false,
            'initialPreview' => $previewImages,
            'overwriteInitial'=>false,
            'multiple' => true
        ]
    ]); ?>
    </div>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>


<script>
    function removeImg(id, itself) {
        $.ajax({
            type: "POST",
            url: "<?=Yii::$app->getUrlManager()->createUrl('gallery-album/remove') ?>",
            data: {
                id : id
            },
            dataType: "html",
            success: function () {
                $(itself[0]).parent().parent().hide();
            }
        });
    }
</script>

backend/views/gallery-album/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\GalleryAlbumSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-album-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'logo') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/gallery-album/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\GalleryAlbum */
/* @var $albumImage common\models\AlbumImage */

$this->title = 'Create Gallery Album';
$this->params['breadcrumbs'][] = ['label' => 'Gallery Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-album-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'albumImage' => $albumImage,
    ]) ?>

</div>

backend/views/gallery-album/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\GalleryAlbumSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Gallery Albums';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-album-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Gallery Album', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'title',
            'description',
            'logo' => [
                'label' => 'Logo',
                'format' => 'html',
                'contentOptions'=>['style'=>'width: 100px;'],
                'value' =>
                    function ($data) {
                        return Html::img($data->logo, ['style' => 'height:100px; max-width:500px']);
                    }
            ],
            [
                'class' => \yii\grid\ActionColumn::className(),
                'buttons'=>[
                    'view'=>function ($url, $model) {
                        $customurl=Yii::$app->getUrlManager()->createUrl(['log/view','id'=>$model['id']]); //$model->id для AR
                        return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $customurl,
                            ['title' => Yii::t('yii', 'View'), 'data-pjax' => '0']);
                    }
                ],
                'template'=>'{update}  {delete}',
            ]
        ],
    ]); ?>

</div>

backend/views/gallery-album/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\GalleryAlbum */

$this->title = 'Update Gallery Album: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Gallery Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="gallery-album-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>